name: Go Refactoring Tool CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures .git directory is available

      - name: Install Dependencies
        run: go mod tidy

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run Linter
        env:
          GOVCS: "off"  # Fully disables Go's VCS checks
        run: golangci-lint run --build-tags -buildvcs=false ./...

      - name: Run Tests
        run: go test -v ./...
